android:
  platformName: Android
  automationName: UIAutomator2
  deviceName: Pixel_8
  udid: ${ANDROID_UDID}
  avd: Pixel_8
  avdLaunchTimeout: 60000
  avdReadyTimeout: 60000
  app: ./builds/zippee-rider-staging.apk
  appPackage: com.zippee.ridercod
  appActivity: com.zippee.ridercod.MainActivity
  autoGrantPermissions: true
  noReset: false
  fullReset: false
  newCommandTimeout: 300

ios:
  platformName: iOS
  automationName: XCUITest
  deviceName: iPhone 15
  udid: ${IOS_UDID}
  app: ./builds/zippee-rider-staging.ipa
  appPackage: com.zippee.ridercod
  autoAcceptAlerts: true
  noReset: false
  newCommandTimeout: 300
